meta_product_name: "The Meetles"
meta_title: "Meetle - Meet in the middle ..."
meta_description: "Whether it's dinner or just a coffee, organise plans in minutes, discover new places, make new memories."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
